version: "3.8"

services:
  app:
    image: finalfuryz/p1_g4_ssd:latest
    restart: always
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    networks:
      - SSDNET
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql_db
    depends_on:
      - mysql_db

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - SSDNET

  mysql_db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - SSDNET
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8888:8000"
      - "8080:8088"
    environment:
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_HOME: /opt/splunk
      SPLUNK_USER: splunk
      SPLUNK_HTTP_ENABLESSL: "true"
      SPLUNK_HTTP_ENABLESSL_CERT: /opt/splunk/etc/auth/certs/fullchain.pem
      SPLUNK_HTTP_ENABLESSL_PRIVKEY: /opt/splunk/etc/auth/certs/privkey.pem
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
    volumes:
      - /opt/splunk/certs/fullchain.pem:/opt/splunk/etc/auth/certs/fullchain.pem:ro
      - /opt/splunk/certs/privkey.pem:/opt/splunk/etc/auth/certs/privkey.pem:ro
      - mysql_data:/mysql_data:ro
      - splunk_data:/opt/splunk/var
      - splunk_etc:/opt/splunk/etc
    networks:
      - SSDNET

volumes:
  mysql_data:
    name: mysql_data
  splunk_data:
  splunk_etc:

networks:
  SSDNET:
    external: true
