version: "3.8"

services:
  app:
    image: finalfuryz/p1_g4_ssd:latest
    restart: always
    networks:
      - SSDNET
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql_db
    depends_on:
      - mysql_db

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - SSDNET

  mysql_db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - SSDNET

volumes:
  mysql_data:

networks:
  SSDNET:
    external: true
